autoload:

  propel:
    name:           propel
    path:           %SF_SYMFONY_LIB_DIR%/plugins/sfPropelPlugin/lib/vendor/propel
    recursive:      on

  propel_addon:
    name:           propel addon
    files:
      Propel:       %SF_SYMFONY_LIB_DIR%/plugins/sfPropelPlugin/lib/propel/sfPropelAutoload.php
